base_info:
  primary_color: "#0066cc"
  title: Orangeer's Blog
  author: 哦润吉
  avatar: /images/Feibajiubi.jpg
  logo: /images/logo.svg
  favicon: /images/logo.svg

menu:
  home: /
  archives: /archives

first_screen:
  enable: false
  background_img: /images/bg.svg
  background_img_dark: /images/bg.svg
  description: Keep writing and Keep loving.
  hitokoto: false

social_contact:
  enable: false
  links:
    github:
    weixin:
    qq:
    weibo:
    zhihu:
    twitter:
    x:
    facebook:
    email:

scroll:
  progress_bar: false
  percent: false
  hide_header: true

home:
  announcement:
  category: false
  tag: false
  post_datetime: updated

post:
  author_badge:
    enable: true
    level_badge: true
    custom_badge: ["One", "Two", "Three"]
  word_count:
    wordcount: false
    min2read: false
  datetime_format: "YYYY-MM-DD HH:mm:ss"
  copyright_info: false
  share: false
  reward:
    enable: false
    img_link:
    text:
    icon:

code_block:
  tools:
    enable: false
    style: default
  highlight_theme: default

toc:
  enable: false
  number: false
  expand_all: false
  init_open: true
  layout: right

website_count:
  busuanzi_count:
    enable: false
    site_uv: false
    site_pv: false
    page_pv: false

local_search:
  enable: false
  preload: false

comment:
  enable: false
  use: valine

rss:
  enable: false

lazyload:
  enable: false

cdn:
  enable: false
  provider: cdnjs

pjax:
  enable: false

footer:
  since: 2020
  word_count: false
  site_deploy:
    enable: false
    provider: cloudflare
    url:
  record:
    enable: false
    list:
      - code:
        link:

inject:
  enable: false
  css: []
  js: []
